import rawArrowLeft from '@iconify-icons/lucide/arrow-left';
import rawArrowRight from '@iconify-icons/lucide/arrow-right';
import rawMaximize from '@iconify-icons/lucide/maximize-2';
import rawBed from '@iconify-icons/lucide/bed';
import rawBath from '@iconify-icons/lucide/bath';
import rawLayers from '@iconify-icons/lucide/layers';
import rawMenu from '@iconify-icons/lucide/menu';
import rawX from '@iconify-icons/lucide/x';
import rawCheck from '@iconify-icons/lucide/check';
import rawCheckCircle from '@iconify-icons/lucide/check-circle';
import rawInfo from '@iconify-icons/lucide/info';
import rawQuote from '@iconify-icons/bi/quote';
import rawApple from '@iconify-icons/simple-icons/apple';
import rawGoogleplay from '@iconify-icons/simple-icons/googleplay';
import rawXTwitter from '@iconify-icons/simple-icons/x';
import rawYoutube from '@iconify-icons/simple-icons/youtube';
import rawInstagram from '@iconify-icons/simple-icons/instagram';
import rawLinkedin from '@iconify-icons/simple-icons/linkedin';

const norm = (i) => i?.default || i;

export const arrowLeft = norm(rawArrowLeft);
export const arrowRight = norm(rawArrowRight);
export const maximize = norm(rawMaximize);
export const bed = norm(rawBed);
export const bath = norm(rawBath);
export const layers = norm(rawLayers);
export const menu = norm(rawMenu);
export const x = norm(rawX);
export const check = norm(rawCheck);
export const checkCircle = norm(rawCheckCircle);
export const info = norm(rawInfo);
export const quote = norm(rawQuote);
export const apple = norm(rawApple);
export const googleplay = norm(rawGoogleplay);
export const xTwitter = norm(rawXTwitter);
export const youtube = norm(rawYoutube);
export const instagram = norm(rawInstagram);
export const linkedin = norm(rawLinkedin);
